### ISSUE TITLE
Add ability to specify a User-Agent HTTP header to requests

### ISSUE THREAD

**Issue by tlim01-github** [ryansmccoy/py-sec-edgar#11]
The EDGAR site is restricting access unless a User-Agent is added to the HTTP header. 

https://www.sec.gov/os/accessing-edgar-data

Possibly add a config parameter in settings.py

**Comment by ryansmccoy** [comment]
Interesting.  If you want to create a pull request and add it to the settings file, go for it!

**Comment by tlim01-github** [comment]
Ok, let me give it a try.
